---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: asset-manager
  namespace: platform-common
spec:
  chart:
    spec:
      chart: asset-manager
      version: ">0.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: airbox-development-charts
        namespace: argocd
  interval: 1m
  values:values: |
{{ .Files.Get "values/1.yaml" | indent 8 }}